from states import *

# TODO organize them into categories
# TODO figure out a way to make this file shared over the network

# communication protocol
CONNECT_TO_SERVER = '0'
ACK_CONNECT_TO_SERVER = '1'
CONNECT_TO_ULTRASONIX = '2'
ACK_CONNECT_TO_ULTRASONIX = '3'
INITIALIZE_IMAGE_ACQUISITION = '4'
ACK_INITIALIZE_IMAGE_ACQUISITION = '5'
START_IMAGE_STREAMING = '6'
ACK_START_IMAGE_STREAMING = '7'
STOP_IMAGE_STREAMING = '8'
ACK_STOP_IMAGE_STREAMING = '9'
QUIT = 'Q'
ACK_QUIT = 'A'

PARAM_INC_DEPTH = 'Z'
PARAM_DEC_DEPTH = 'X'
PARAM_GET_DEPTH = 'C'

PARAM_INC_GAIN = 'V'
PARAM_DEC_GAIN = 'B'
PARAM_GET_GAIN = 'N'

PARAM_INC_FREQ = 'M'
PARAM_DEC_FREQ = 'L'
PARAM_GET_FREQ = 'K'

PARAM_INC_FOCUS = 'J'
PARAM_DEC_FOCUS = 'H'
PARAM_GET_FOCUS = 'G'

PARAM_FREEZE_TOGGLE = 'F'

# server constants
SONIX_TIMEOUT = 250
LOCAL_SONIX_ADDRESS = 'localhost'
SONIX_FAIL_MAX_COUNT = 100

SERVER_ADDRESS = '192.168.0.1'
SERVER_PARAM_PORT = 8089
SERVER_IMAGE_PORT = 10000

SERIALIZED_IMAGE_SIZE = 5024000
OPTIMAL_IMAGE_WIDTH = 1092
OPTIMAL_IMAGE_HEIGHT = 758




